trigger:
- main

pool:
  name: 'Test1'

steps:
- script: |
    python3 --version
    python3 -m pip install --upgrade pip
    python3 -m pip install -r requirements.txt
  displayName: 'Install Python dependencies'

- script: |
    sudo systemctl start mongod
    sudo systemctl status mongod --no-pager
  displayName: 'Start MongoDB'

- script: |
    mkdir -p junit
    MONGO_URI="mongodb://localhost:27017/test_student_db" python3 -m pytest test_app.py --junitxml=junit/test-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'junit/test-results.xml'
    testRunTitle: 'Flask Pytest Results'
  displayName: 'Publish test results'